"""Generate a complete LS-DYNA keyword file for TNT spherical blast.

Reads physical parameters from ``configs/tnt_spherical.yaml`` and writes
``tnt_blast.k`` with:
- 2D axisymmetric ALE mesh (TNT + air)
- JWL EOS for TNT (Lee-Tarver 1980)
- Linear polynomial EOS for air (ideal gas)
- Point detonation at origin
- Non-reflecting boundary at R_far
- Tracers at key radii for time-history extraction

Unit system: g-mm-ms  (so numbers look normal-sized in LS-PrePost).

Usage
-----
    python -m data.generate_lsdyna_input --config configs/tnt_spherical.yaml
    # -> writes ./tnt_blast.k

    ls-dyna i=tnt_blast.k memory=500m ncpu=4
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import yaml


# ============================================================= unit conversion
# SI -> g-mm-ms
#   length:   m  -> mm     (×1e3)
#   mass:     kg -> g      (×1e3)
#   time:     s  -> ms     (×1e3)
#   density:  kg/m^3 -> g/mm^3       (×1e-6)
#   velocity: m/s -> mm/ms           (×1)  (cancels)
#   pressure: Pa = kg/(m s^2) -> g/(mm ms^2) = MPa   (×1e-6)
#   energy density: J/m^3 = Pa -> MPa                (×1e-6)


def si_to_gmmms(cfg: dict) -> dict:
    """Convert relevant SI quantities to g-mm-ms."""
    exp = cfg["explosive"]
    air = cfg["air"]
    pre = cfg["preprocessing"]

    # Charge radius from mass: W = (4/3) pi R0^3 rho0
    W      = exp["W"]       # kg
    rho0_SI = exp["rho0"]   # kg/m^3
    R0_m    = (3.0 * W / (4.0 * math.pi * rho0_SI)) ** (1.0 / 3.0)

    return {
        "R0_mm":     R0_m * 1e3,                       # charge radius in mm
        "R_far_mm":  1000.0,                           # 1 m = 1000 mm
        "rho0_gpm3": rho0_SI * 1e-6,                   # TNT density in g/mm^3
        "D_CJ_mpms": exp["D_CJ"] * 1e-3,               # m/s -> mm/ms (×1e-3? No: ×1)
        # Wait: 1 m/s = 1000 mm / 1000 ms = 1 mm/ms. So D_CJ stays numerically same.
        "D_CJ":      exp["D_CJ"] * 1.0,                # mm/ms, same number as m/s
        "P_CJ_MPa":  0.5 * rho0_SI * exp["D_CJ"] ** 2 / (1 + 0.3) * 1e-6,  # rough
        "A_MPa":     exp["jwl"]["A"]   * 1e-6,
        "B_MPa":     exp["jwl"]["B"]   * 1e-6,
        "R1":        exp["jwl"]["R1"],
        "R2":        exp["jwl"]["R2"],
        "omega":     exp["jwl"]["omega"],
        "E0_MPa":    exp["jwl"]["E0"]  * 1e-6,         # J/m^3 -> MPa
        "gamma":     air["gamma"],
        "rho_a_gpm3": air["rho_a"]     * 1e-6,
        "P_a_MPa":   air["P_a"]        * 1e-6,
        "E_a_MPa":   air["P_a"] / (air["gamma"] - 1.0) * 1e-6,
        "t_end_ms":  cfg["domain"]["t_end"] * 1e3,
    }


# ============================================================= mesh generation


def generate_mesh(R0_mm: float, R_far_mm: float,
                  n_tnt: int, n_air: int,
                  y_thick: float = 1.0) -> tuple[list, list]:
    """Build 2D axisymmetric mesh: a thin strip along r-axis.

    Nodes live in the (x, y) plane; y is the "thickness" direction (1 element).
    LS-DYNA ELFORM=15 interprets x as r (radial) axis.

    Returns
    -------
    nodes : list of (nid, x, y, z)
    elems : list of (eid, pid, n1, n2, n3, n4)
    """
    nodes = []
    elems = []

    # Combined r grid: concatenate TNT and Air parts
    r_tnt = [R0_mm * i / n_tnt for i in range(n_tnt + 1)]
    r_air = [R0_mm + (R_far_mm - R0_mm) * i / n_air for i in range(1, n_air + 1)]
    r_all = r_tnt + r_air   # length = n_tnt + 1 + n_air

    n_r = len(r_all)

    # Two rows of nodes: y=0 and y=y_thick
    # node id layout: row 0 (y=0) ids 1..n_r; row 1 (y=y_thick) ids n_r+1..2*n_r
    for i, r in enumerate(r_all):
        nodes.append((i + 1, r, 0.0, 0.0))
    for i, r in enumerate(r_all):
        nodes.append((n_r + i + 1, r, y_thick, 0.0))

    # Elements: quad4; TNT -> pid 1, Air -> pid 2
    for i in range(n_r - 1):
        n1 = i + 1
        n2 = i + 2
        n3 = n_r + i + 2
        n4 = n_r + i + 1
        pid = 1 if i < n_tnt else 2
        elems.append((i + 1, pid, n1, n2, n3, n4))

    return nodes, elems


# ============================================================= keyword writer


def write_keyword(path: Path, cfg: dict, u: dict,
                  n_tnt: int = 50, n_air: int = 500) -> None:
    """Emit the complete tnt_blast.k file."""
    nodes, elems = generate_mesh(
        R0_mm=u["R0_mm"], R_far_mm=u["R_far_mm"],
        n_tnt=n_tnt, n_air=n_air,
    )

    # Tracer radii (mm) — spread across the air region
    tracers = [u["R0_mm"], 100.0, 200.0, 300.0, 500.0, 800.0]

    lines = []
    push = lines.append

    # ------------------------------------------------------------ header
    push("*KEYWORD")
    push("*TITLE")
    push("TNT Spherical Blast 1kg - generated by generate_lsdyna_input.py")
    push("$ Unit system: g-mm-ms (length=mm, mass=g, time=ms, pressure=MPa)")
    push(f"$ TNT radius R0 = {u['R0_mm']:.4f} mm, R_far = {u['R_far_mm']:.1f} mm")

    # ------------------------------------------------------------ control
    push("*CONTROL_ALE")
    push("$   DCT    NADV   METH   AFAC   BFAC   CFAC   DFAC   EFAC")
    push("      2       1      3   -1.0    0.0    0.0    0.0    0.0")
    push("*CONTROL_TERMINATION")
    push("$  ENDTIM")
    push(f"  {u['t_end_ms']:.4f}")
    push("*CONTROL_TIMESTEP")
    push("$  DTINIT    TSSFAC")
    push("      0.0       0.5")

    # ------------------------------------------------------------ database
    push("*DATABASE_GLSTAT")
    push("  1.0e-3")
    push("*DATABASE_BINARY_D3PLOT")
    push("$       DT")
    push(f"  {u['t_end_ms'] / 300.0:.6f}")   # ~300 frames
    push("*DATABASE_BINARY_D3THDT")
    push("  1.0e-3")
    push("*DATABASE_TRHIST")
    push("  1.0e-3")
    push("*DATABASE_HISTORY_NODE_LOCAL")

    # ------------------------------------------------------------ materials
    push("$ ============ TNT ============")
    push("*MAT_HIGH_EXPLOSIVE_BURN")
    push("$      MID         RO            D         PCJ")
    push(f"         1  {u['rho0_gpm3']:.4e}  {u['D_CJ']:.1f}  {u['P_CJ_MPa']:.4e}")
    push("*EOS_JWL")
    push("$    EOSID          A          B        R1        R2     OMEGA         E0        V0")
    push(f"         1  {u['A_MPa']:.4e}  {u['B_MPa']:.4e}  {u['R1']:.3f}  {u['R2']:.3f}  {u['omega']:.3f}  {u['E0_MPa']:.4e}     1.000")
    push("*PART")
    push("TNT explosive")
    push("$      PID     SECID       MID     EOSID")
    push("         1         1         1         1")

    push("$ ============ Air ============")
    push("*MAT_NULL")
    push("$      MID         RO")
    push(f"         2  {u['rho_a_gpm3']:.4e}")
    push("*EOS_LINEAR_POLYNOMIAL")
    push("$    EOSID        C0        C1        C2        C3        C4        C5")
    g_m1 = u["gamma"] - 1.0
    push(f"         2       0.0       0.0       0.0       0.0  {g_m1:.3f}  {g_m1:.3f}")
    push("$                  C6            E0        V0")
    push(f"                 0.0  {u['E_a_MPa']:.4e}     1.000")
    push("*PART")
    push("Air")
    push("$      PID     SECID       MID     EOSID")
    push("         2         1         2         2")

    # ------------------------------------------------------------ section
    push("$ ============ Section (2D Axisymmetric ALE Euler) ============")
    push("*SECTION_SHELL")
    push("$    SECID    ELFORM")
    push("         1        15")
    push("$ ELFORM=15: 2D axisymmetric ALE; x = r, y = axial (dummy for 1D-radial)")

    # ------------------------------------------------------------ nodes
    push("$ ============ Nodes ============")
    push("*NODE")
    push("$      NID               X               Y               Z")
    for nid, x, y, z in nodes:
        push(f"  {nid:>8d}  {x:14.6f}  {y:14.6f}  {z:14.6f}")

    # ------------------------------------------------------------ elements
    push("$ ============ Elements ============")
    push("*ELEMENT_SHELL")
    push("$      EID       PID        N1        N2        N3        N4")
    for eid, pid, n1, n2, n3, n4 in elems:
        push(f"  {eid:>8d}  {pid:>8d}  {n1:>8d}  {n2:>8d}  {n3:>8d}  {n4:>8d}")

    # ------------------------------------------------------------ detonation
    push("$ ============ Detonation at origin ============")
    push("*INITIAL_DETONATION")
    push("$      PID         X         Y         Z        LT")
    push("         1       0.0       0.0       0.0       0.0")

    # ------------------------------------------------------------ boundary
    push("$ ============ Non-reflecting outer boundary ============")
    # Rightmost column of nodes (at r = R_far):
    n_r = n_tnt + n_air + 1
    right_nodes = [n_r, 2 * n_r]
    push("*SET_NODE_LIST")
    push("$      SID")
    push("         1")
    push("$     NID1      NID2")
    push(f"  {right_nodes[0]:>8d}  {right_nodes[1]:>8d}")
    push("*BOUNDARY_NON_REFLECTING")
    push("$     SSID")
    push("         1")

    # Axis (y = 0) symmetry: constrain y-displacement
    push("$ ============ Axis symmetry (y=0 line) ============")
    bot_row = [nid for nid, _, yy, _ in nodes if yy == 0.0]
    push("*SET_NODE_LIST")
    push("         2")
    # write 8 per line
    for i in range(0, len(bot_row), 8):
        chunk = bot_row[i:i + 8]
        push("  " + "  ".join(f"{n:>8d}" for n in chunk))
    push("*BOUNDARY_SPC_SET")
    push("$     NSID       CID      DOFX      DOFY      DOFZ     DOFRX     DOFRY     DOFRZ")
    push("         2         0         0         1         1         1         1         1")

    # ------------------------------------------------------------ tracers
    push("$ ============ ALE Tracers (time history) ============")
    for i, r_mm in enumerate(tracers, start=1):
        push("*DATABASE_TRACER")
        push("$       ID    TRACK               X               Y               Z")
        push(f"  {i:>8d}         2  {r_mm:14.6f}           0.000           0.000")

    push("*END")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ============================================================= main


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/tnt_spherical.yaml")
    ap.add_argument("--output", default="tnt_blast.k")
    ap.add_argument("--n-tnt", type=int, default=50,
                    help="Number of elements inside TNT (r=0 to R0)")
    ap.add_argument("--n-air", type=int, default=500,
                    help="Number of elements in air (r=R0 to R_far)")
    args = ap.parse_args()

    cfg_path = Path(args.config)
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))

    u = si_to_gmmms(cfg)

    out = Path(args.output)
    write_keyword(out, cfg, u, n_tnt=args.n_tnt, n_air=args.n_air)

    print(f"[OK] wrote {out}")
    print(f"     TNT radius  R0 = {u['R0_mm']:.4f} mm")
    print(f"     outer bound R_far = {u['R_far_mm']:.1f} mm")
    print(f"     mesh: {args.n_tnt} TNT + {args.n_air} air elements")
    print(f"     end time = {u['t_end_ms']:.2f} ms")
    print()
    print("Run with:")
    print(f"     ls-dyna i={out} memory=500m ncpu=4")


if __name__ == "__main__":
    main()
